const EXACT_MEANING_OVERRIDES: Record<string, string> = {
  'в': 'in',
  'у': 'at',
  'есть': 'there is',
  'быть': 'to be',
  'один': 'one',
  'одна': 'one',
  'одно': 'one',
  'я': 'I',
  'ты': 'you',
  'он': 'he',
  'она': 'she',
  'оно': 'it',
  'мы': 'we',
  'они': 'they',
  'мама': 'mom',
  'моя': 'my',
  'папа': 'dad',
  'бабушка': 'grandmother',
  'дедушка': 'grandfather',
  'дом': 'house',
  'вода': 'water',
  'кофе': 'coffee',
  'чай': 'tea',
  'хлеб': 'bread',
  'сахар': 'sugar',
  'молоко': 'milk',
  'стол': 'table',
  'стул': 'chair',
  'комната': 'room',
  'адрес': 'address',
  'карта': 'map',
  'фото': 'photo',
  'яблоко': 'apple',
  'лимон': 'lemon',
  'линия': 'line',
  'бумага': 'paper',
  'пакет': 'bag',
  'цена': 'price',
  'почта': 'post office',
  'парк': 'park',
  'такси': 'taxi',
  'поезд': 'train',
  'стена': 'wall',
  'море': 'sea',
  'луна': 'moon',
  'сеть': 'net',
  'рис': 'rice',
  'костюм': 'suit',
  'природа': 'nature',
  'лодка': 'boat',
  'озеро': 'lake',
  'мир': 'peace',
  'земля': 'earth',
  'солнце': 'sun',
  'рыба': 'fish',
  'кошка': 'cat',
  'собака': 'dog',
  'ребёнок': 'child',
  'мужчина': 'man',
  'женщина': 'woman',
  'рука': 'hand',
  'голова': 'head',
  'копия': 'copy',
  'шар': 'ball',
  'вершина': 'top',
  'шея': 'neck',
  'кубик': 'dice',
  'дата': 'date',
  'зуб': 'tooth',
  'банк': 'bank',
  'край': 'edge',
  'красивая': 'beautiful',
  'год': 'year',
  'неделя': 'week',
  'время': 'time',
  'сегодня': 'today',
  'сейчас': 'now',
  'никогда': 'never',
  'где': 'where',
  'какой': 'which',
  'сколько': 'how much',
  'кто': 'who',
  'что': 'what',
  'этот': 'this',
  'эта': 'this',
  'это': 'this',
  'да': 'yes',
  'нет': 'no',
  'хорошо': 'good',
  'холодно': 'cold',
  'маленький': 'small',
  'короткий': 'short',
  'милый': 'cute',
  'молодой': 'young',
  'пустой': 'empty',
  'громко': 'loudly',
  'наверху': 'upstairs',
  'там': 'there',
  'здесь': 'here',
  'делать': 'to do',
  'читать': 'to read',
  'учить': 'to study',
  'идти': 'to go',
  'жить': 'to live',
  'делай вместе': 'do it together',
  'достаточно': 'enough',
  'охотно': 'gladly',
  'пойдём со мной': 'come with me',
  'я здесь': 'I am here',
  'он здесь': 'he is here',
  'она здесь': 'she is here',
  'кофе здесь': 'the coffee is here',
  'чай здесь': 'the tea is here',
  'папа здесь': 'dad is here',
  'она милая': 'she is cute',
  'он милый': 'he is cute',
  'ты учишься': 'you study',
  'ты наверху': 'you are upstairs',
  'они едят': 'they are eating',
  'я играю': 'I am playing',
  'я сделаю это': 'I will do it',
  'я могу это': 'I can do it',
  'ты мне нравишься': 'I like you',
  'я люблю маму': 'I love mom',
  'ты любишь море': 'you love the sea',
  'хлеб и мир': 'bread and peace',
  'красивая лодка': 'beautiful boat',
  'озеро и фото': 'lake and photo',
  'у меня есть вода': 'I have water',
  'йога и джаз': 'yoga and jazz',
  'где ты': 'where are you',
  'да, пожалуйста': 'yes, please',
  'вы говорите по-английски?': 'Do you speak English?',
  'вы говорите по-русски?': 'Do you speak Russian?',
  'я немного говорю по-английски': 'I speak a little English',
  'как это сказать по-английски?': 'How do you say this in English?',
  'здравствуйте': 'hello',
  'привет': 'hi',
  'доброе утро': 'good morning',
  'добрый день': 'good afternoon',
  'добрый вечер': 'good evening',
  'спокойной ночи': 'good night',
  'до свидания': 'goodbye',
  'до скорого': 'see you soon',
  'увидимся': 'see you',
  'пока': 'bye',
  'спасибо': 'thank you',
  'большое спасибо': 'thank you very much',
  'не за что': 'you are welcome',
  'извините': 'excuse me',
  'простите': 'sorry',
  'мне жаль': 'I am sorry',
  'ничего страшного': 'it is okay',
  'будьте здоровы': 'bless you',
  'конечно': 'of course',
  'правильно': 'correct',
  'повторите': 'repeat, please',
  'медленно': 'slowly',
  'говорите медленнее': 'speak more slowly',
  'немного': 'a little',
  'много': 'a lot',
  'так себе': 'so-so',
  'а вы?': 'and you?',
  'приятно познакомиться': 'nice to meet you',
  'очень приятно': 'very nice to meet you',
  'вы откуда?': 'where are you from?',
  'откуда вы?': 'where are you from?',
  'помогите': 'help',
  'помощь': 'help',
  'близко': 'near',
  'далеко': 'far',
  'направо': 'to the right',
  'налево': 'to the left',
  'прямо': 'straight',
  'вызовите врача': 'call a doctor',
  'вызовите скорую': 'call an ambulance',
  'вызовите скорую помощь': 'call an ambulance',
  'сколько стоит?': 'how much is it?',
  'сколько стоит килограмм?': 'how much is a kilogram?',
  'дорого': 'expensive',
  'дёшево': 'cheap',
  'можно картой?': 'can I pay by card?',
  'можно оплатить картой?': 'can I pay by card?',
  'хочу': 'I want',
  'не хочу': 'I do not want',
  'вкусно': 'tasty',
  'вино': 'wine',
  'ваза': 'vase',
  'лицо': 'face',
  'камень': 'stone',
  'шёлк': 'silk',
  'улица': 'street',
  'вечер': 'evening',
  'голод': 'hunger',
  'дым': 'smoke',
  'мороженое': 'ice cream',
  'фигура': 'figure',
  'побег': 'escape',
  'горло': 'throat',
  'картина': 'picture',
  'ноль': 'zero',
  'дядя': 'uncle',
  'рюкзак': 'backpack',
  'пицца': 'pizza',
  'кусок': 'piece',
  'зона': 'zone',
  'половина': 'half',
  'зебра': 'zebra',
  'станция': 'station',
  'джинсы': 'jeans',
  'джаз': 'jazz',
  'киви': 'kiwi',
  'интернет': 'web',
  'вайфай': 'wifi',
  'ксилофон': 'xylophone',
  'каяк': 'kayak',
  'йети': 'yeti',
  'остро?': 'is it spicy?',
  'который час?': 'what time is it?',
  'картой': 'by card',
  'наличными': 'cash',
  'меню': 'menu',
  'счёт': 'bill',
  'воды': 'water',
  'аптека': 'pharmacy',
  'аэропорт': 'airport',
  'вокзал': 'train station',
  'метро': 'metro',
  'отель': 'hotel',
  'туалет': 'toilet',
  'плохо': 'bad',
  'всё хорошо': 'everything is fine',
  'почему?': 'why?',
  'можете взвесить?': 'can you weigh it?',
  'евро': 'euro',
  'цент': 'cent',
  'лари': 'lari',
  'тетри': 'tetri',
  'динар': 'dinar',
  'пара': 'para',
  'лира': 'lira',
  'куруш': 'kurus',
  'два': 'two',
  'три': 'three',
  'четыре': 'four',
  'пять': 'five',
  'шесть': 'six',
  'семь': 'seven',
  'восемь': 'eight',
  'девять': 'nine',
  'десять': 'ten',
  'одиннадцать': 'eleven',
  'двенадцать': 'twelve',
  'пятнадцать': 'fifteen',
  'двадцать': 'twenty',
  'тридцать': 'thirty',
  'пятьдесят': 'fifty',
  'сто': 'one hundred',
  'пятьсот': 'five hundred',
  'тысяча': 'one thousand',
  'пятнадцать минут': 'fifteen minutes',
  'тридцать минут': 'thirty minutes',
  'пять евро': 'five euros',
  'десять евро': 'ten euros',
  'пятьдесят центов': 'fifty cents',
  'пять лари': 'five lari',
  'десять лари': 'ten lari',
  'пятьдесят тетри': 'fifty tetri',
  'пять динаров': 'five dinars',
  'сто динаров': 'one hundred dinars',
  'пятьсот динаров': 'five hundred dinars',
  'пять лир': 'five lira',
  'сто лир': 'one hundred lira',
  'пятьсот лир': 'five hundred lira',
  'разрешите пройти': 'let me pass',
  'э рисит плиз': 'a receipt, please',
  'э бэг плиз': 'a bag, please',
  'зэ меню плиз': 'the menu, please',
  'фор хиэ плиз': 'for here, please',
  'ту гоу плиз': 'to go, please',
  'зэ бил плиз': 'the bill, please',
  'ноу сэнк ю': 'no, thank you',
  'лет ми пас плиз': 'let me pass, please',
  'гоу эхэд плиз': 'go ahead, please',
  'репетэ силь ву пле': 'repeat, please',
  'лядисьон силь ву пле': 'the bill, please',
  'эн кафе силь ву пле': 'a coffee, please',
  'вот': 'here',
  'фиалка': 'violet',
  'что-нибудь': 'something',
  'дверь': 'door',
  'школа': 'school',
  'хороший': 'good',
  'корабль': 'ship',
  'девочка': 'girl',
  'сердце': 'heart',
  'кино': 'cinema',
  'ручка': 'pen',
  'пиво': 'beer',
  'большой': 'big',
  'рот': 'mouth',
  'сок': 'juice',
  'волосы': 'hair',
  'нос': 'nose',
  'сон': 'sleep',
  'село': 'village',
  'лес': 'forest',
  'лист': 'leaf',
  'квартира': 'apartment',
  'сестра': 'sister',
  'брат': 'brother',
  'еда': 'food',
  'мята': 'mint',
  'позвони': 'call',
  'позови маму': 'call mom',
  'что ищешь?': 'what are you looking for?',
  'найди мяту': 'find the mint',
  'гранат': 'pomegranate',
  'колыбельная': 'lullaby',
  'твоей маме': 'for your mom',
  'штука': 'piece',
  'мука': 'flour',
  'свеча': 'candle',
  'синий': 'blue',
  'счастливый': 'happy',
  'держи': 'take it',
  'порт': 'port',
  'текст': 'text',
  'стой': 'stop',
  'имя': 'name',
  'симит': 'simit',
  'ладно': 'okay',
  'последний': 'last',
  'вопрос': 'question',
  'две вещи': 'two things',
  'дай мне': 'give me',
  'восемь фиалок': 'eight violets',
  'где школа?': 'where is the school?',
  'она носит': 'she is wearing it',
  'мой дом': 'my house',
  'что-что?': 'what what?',
  'мама, что?': 'mom, what?',
  'это коробка': 'this is a box',
  'дай мне муку': 'give me flour',
  'эта комната': 'this room',
  'к этому': 'to this',
  'этот медведь': 'this bear',
  'один момент': 'one moment',
  'твой дом': 'your house',
  'мне нравится': 'I like it',
  'чай тоже': 'tea too',
  'не': 'not',
  'пусть будет': 'let it be',
  'медведь': 'bear',
  'роза': 'rose',
  'золото': 'gold',
  'странный': 'strange',
  'ошибка': 'error',
  'та': 'that',
  'тот': 'that',
  'музей': 'museum',
  'но': 'but',
  'груша': 'pear',
  'пьёт': 'drinks',
  'жизнь': 'life',
  'видеть': 'to see',
  'иду домой': 'I am going home',
  'кот': 'cat',
  'люди': 'people',
  'зелёный': 'green',
  'серьёзный': 'serious',
  'гнездо': 'nest',
  'тест': 'test',
  'страница': 'page',
  'гусь': 'goose',
  'мышь': 'mouse',
  'цвет': 'color',
  'так': 'so',
  'тоже': 'too',
  'овёс': 'oats',
  'палец ноги': 'toe',
  'место': 'seat',
  'тост': 'toast',
  'ешь тост': 'eat toast',
  'штат': 'state',
  'вкус': 'taste',
  'рядом': 'near',
  'дерево': 'tree',
  'я побежал': 'I ran',
  'дождь': 'rain',
  'нет дождя': 'no rain',
  'магазин': 'store',
  'его': 'his',
  'её': 'her',
  'впусти её': 'let her in',
  'то': 'that',
  'старый': 'old',
  'держи это': 'hold this',
  'слушать': 'to listen',
  'остров': 'island',
  'заходи': 'come in',
  'нас': 'us',
  'резать': 'to cut',
  'намного больше': 'much more',
  'должен': 'must',
  'музыка': 'music',
  'считать': 'to count',
  'человек': 'person',
  'вернуться': 'to return',
  'вверх': 'up',
  'возьми чашку': 'grab a cup',
  'большая чашка': 'big cup',
  'сумка': 'bag',
  'кровать': 'bed',
  'плохой': 'bad',
  'стоп': 'stop',
  'группа': 'group',
  'начинать': 'to begin',
  'проблема': 'problem',
  'мы чувствуем себя в безопасности': 'we feel safe',
  'путь': 'way',
  'новый': 'new',
  'ты можешь летать': 'you can fly',
  'несколько': 'a few',
  'семья': 'family',
  'друг': 'friend',
  'мой друг здесь': 'my friend is here',
  'ключ': 'key',
  'книга': 'book',
  'работа': 'work',
  'мне нравится моя работа': 'I like my work',
  'очень добрый': 'very kind',
  'знать': 'to know',
  'держать': 'to keep',
  'брать': 'to take',
  'почини это': 'fix this',
  'каждый': 'every',
  'кухня': 'kitchen',
  'пример': 'example',
  'зоопарк': 'zoo',
  'размер': 'size',
  'приз': 'prize',
  'просто': 'just',
  'шутка': 'joke',
  'просто шутка': 'just a joke',
  'прыгать': 'to jump',
  'тихий': 'quiet',
  'быстрый': 'quick',
  'джаз — это весело': 'jazz is fun',
  'артикль (м. р.)': 'masculine article',
  'артикль (ж. р.)': 'feminine article',
  'он читает': 'he reads',
  'она читает': 'she reads',
  'соль': 'salt',
  'грязный': 'dirty',
  'крыса': 'rat',
  'искусство': 'art',
  'крыло': 'wing',
  'одна (артикль)': 'a/an (feminine article)',
  'моё имя': 'my name',
  'мой друг': 'my friend',
  'понедельник': 'Monday',
  'один (артикль м. р.)': 'a/an (masculine article)',
  'хлеб хороший': 'the bread is good',
  'нога': 'leg',
  'белый': 'white',
  'палец': 'finger',
  'фирма': 'company',
  'руку': 'hand',
  'шапку': 'hat',
  'воду': 'water',
  'чая': 'tea',
  'соли': 'salt',
  'кота': 'cat',
  'тишина': 'silence',
  'часы': 'clock',
  'велосипед': 'bicycle',
  'автобус': 'bus',
  'пол': 'floor',
  'июнь': 'June',
  'июль': 'July',
  'план': 'plan',
  'отец': 'father',
  'коробка': 'box',
  'смесь': 'mixture',
  'печенье': 'cookie',
  'чек': 'receipt',
  'творог': 'cottage cheese',
  'йога': 'yoga',
  'вечеринка': 'party',
  'мобильник': 'mobile phone',
  'малыш': 'baby',
  'центр города': 'city center',
  'окей': 'okay',
  'тест нормальный': 'the test is okay',
  'факс': 'fax',
  'сыр': 'cheese',
  'март': 'March',
  'поздно': 'late',
  'руки': 'hands',
  'горячий': 'hot',
  'горячее': 'hot',
  'яблоки': 'apples',
  'веселье': 'fun',
  'зовусь': 'am called',
  'следующий': 'next',
  'снаружи': 'outside',
  'дверь закрыта': 'the door is closed',
  'над': 'above',
  'мусор': 'trash',
  'масло': 'butter',
  'слышать': 'to hear',
  'красиво': 'beautiful',
  'кёльн': 'Cologne',
  'завтрак': 'breakfast',
  'возможно': 'possible',
  'ложка': 'spoon',
  'уставший': 'tired',
  'качество': 'quality',
  'тип': 'type',
  'система': 'system',
  'люди помогают': 'people help',
  'почему': 'why',
  'история': 'story',
  'нравится': 'likes',
  'быстрый тест': 'quick test',
  'вещь': 'thing',
  'ужин': 'dinner',
  'медленный': 'slow',
  'жара': 'heat',
  'класс': 'class',
  'если': 'if',
  'деньги': 'money',
  'бог': 'god',
  'порядок': 'order',
  'здоровый': 'healthy',
  'ходить': 'to walk',
  'арбуз': 'watermelon',
  'уже': 'already',
  'лёд': 'ice',
  'остаюсь': 'I stay',
  'услуга': 'service',
  'очередь': 'line',
  'счастливого дня': 'have a nice day',
  'легко': 'easy',
  'свежий сок': 'fresh juice',
  'игра': 'game',
  'красный': 'red',
  'начальник': 'boss',
  'сад': 'garden',
  'мальчик': 'boy',
  'сеньор': 'sir',
  'сеньора': 'madam',
  'дополнительный сыр': 'extra cheese',
  'испания': 'Spain',
  'экзамен': 'exam',
  'мексика': 'Mexico',
  'точно': 'exactly',
  'караоке': 'karaoke',
  'коала': 'koala',
  'кебаб': 'kebab',
  'сайт': 'website',
  'виски': 'whisky',
  'киоск': 'kiosk',
  'шоу': 'show',
  'вок': 'wok',
  'вики': 'wiki',
  'выходные': 'weekend',
  'английский': 'English',
  'быстро': 'fast',
  'номер': 'number',
  'пингвин': 'penguin',
  'стыд': 'shame',
  'двуязычный': 'bilingual',
  'большой парк': 'big park',
  'картинка': 'picture',
  'справедливо': 'fair',
  'гараж': 'garage',
  'газ': 'gas',
  'идея': 'idea',
  'страна': 'country',
  'очень': 'very',
  'официант': 'waiter',
  'французский': 'French',
  'мать': 'mother',
  'праздник': 'holiday',
  'возраст': 'age',
  'торт': 'cake',
  'замок': 'castle',
  'уверенный': 'confident',
  'кукуруза': 'corn',
  'рождество': 'Christmas',
  'яйцо': 'egg',
  'находится': 'located',
  'нужно': 'needed',
  'запах': 'smell',
  'погода': 'weather',
  'билет': 'ticket',
  'тёплый': 'warm',
  'тёплое': 'warm',
  'полка': 'shelf',
  'лапа': 'paw',
  'томат': 'tomato',
  'шапка': 'hat',
  'город': 'city',
  'курица': 'chicken',
  'пальто': 'coat',
  'помидор': 'tomato',
  'ветер': 'wind',
  'копейка': 'coin',
  'журнал': 'magazine',
  'куртка': 'jacket',
  'чёрный': 'black',
  'середина': 'middle',
  'люблю': 'I love',
  'шоти': 'shoti',
  'страх': 'fear',
  'холодный': 'cold',
  'птица': 'bird',
  'небо': 'sky',
  'мясо': 'meat',
  'дорогой': 'expensive',
  'стакан': 'glass',
  'хачапури': 'khachapuri',
  'шашлык': 'shashlik',
  'ночь': 'night',
  'умный': 'smart',
  'свинья': 'pig',
  'какая цена': 'what is the price',
  'кафе': 'cafe',
  'джем': 'jam',
  'каша': 'porridge',
  'апельсин': 'orange',
  'телефон': 'phone',
  'карандаш': 'pencil',
  'офис': 'office',
  'двор': 'yard',
  'дорога': 'road',
  'из-за': 'because of',
  'всем привет': 'hello everyone',
  'зима': 'winter',
  'гора': 'mountain',
  'знак': 'sign',
  'царь': 'tsar',
  'цветок': 'flower',
  'церковь': 'church',
  'чистый': 'clean',
  'гуляю': 'I walk',
  'учу': 'I study',
  'хочу пить': 'I want to drink',
  'жёлтый': 'yellow',
  'нож': 'knife',
  'муж': 'husband',
  'говорит': 'speaks',
  'фильм': 'film',
  'бутылка': 'bottle',
  'шеф': 'boss',
  'любовь': 'love',
  'лучше': 'better',
  'её дом': 'her house',
  'конь': 'horse',
  'меньше': 'less',
  'воля': 'will',
  'поле': 'field',
  'ей': 'to her',
  'им': 'to them',
  'целует': 'kisses',
  'ученик': 'student',
  'спина': 'back',
  'подойди': 'come closer',
  'младший': 'younger',
  'мочь': 'to be able to',
  'домой': 'home',
  'карман': 'pocket',
  'свитер': 'sweater',
  'здание': 'building',
  'кто-то': 'someone',
  'дай': 'give',
  'снова': 'again',
  'господин': 'sir',
  'перец': 'pepper',
  'месяц': 'month',
  'талия': 'waist',
  'мёд': 'honey',
  'ясный': 'clear',
  'знай': 'know',
  'даже': 'even',
  'язык': 'language',
  'останься': 'stay',
  'кекс': 'cupcake',
  'иди сюда': 'come here',
  'приходи к нам': 'come to us',
  'иди': 'go',
  'лето': 'summer',
  'длинный': 'long',
  'разрешение': 'permission',
  'очень остро': 'very spicy',
  'голодный': 'hungry',
  'открыто': 'open',
  'приятный': 'pleasant',
  'больной': 'sick',
  'сразу': 'right away',
  'совсем': 'completely',
  'рынок': 'market',
  'виноград': 'grapes',
  'слово': 'word',
  'глаз': 'eye',
  'задание': 'task',
  'правый': 'right',
  'приятного аппетита': 'enjoy your meal',
  'самолёт': 'airplane',
  'японец': 'Japanese man',
  'лезвие': 'blade',
  'сообщение': 'message',
  'один кофе': 'one coffee',
  'свежий киви': 'fresh kiwi',
  'вайфай работает': 'the wifi works',
  'бесплатный сайт': 'free website',
  'ещё чай': 'more tea',
  'моя сестра': 'my sister',
  'на вокзал': 'to the station',
  'очень хорошо': 'very good',
  'фильм хороший': 'the film is good',
  'жёлтый стакан': 'yellow glass',
  'стакан чистый': 'the glass is clean',
  'чай готов': 'the tea is ready',
  'пей чай': 'drink tea',
  'дай деньги': 'give me the money',
  'сделай фото': 'take a photo',
  'слишком много': 'too much',
  'да, это здесь': 'yes, it is here',
  'меня зовут анна': 'my name is Anna',
  'я так не думаю': 'I do not think so',
  'это не серьёзно': 'this is not serious',
  'есть вода': 'there is water',
  'есть сыр': 'there is cheese',
  'хочу сыр': 'I want cheese',
  'я был счастлив': 'I was happy',
  'счастливый мальчик': 'happy boy',
  'завтра пойду': 'I will go tomorrow',
  'я могу считать': 'I can count',
  'не нужно': 'not needed',
  'хочу немного чая': 'I want a little tea',
  'я хочу воду': 'I want water',
  'хочу воду': 'I want water',
  'дай мне руку': 'give me your hand',
  'скажи мне': 'tell me',
  'дай кота': 'give me the cat',
  'немного соли': 'a little salt',
  'поцелуй меня': 'kiss me',
  'йога — это хорошо': 'yoga is good',
};

const TOKEN_MAP: Record<string, string> = {
  'и': 'and',
  'в': 'in',
  'на': 'on',
  'под': 'under',
  'с': 'with',
  'без': 'without',
  'для': 'for',
  'из': 'from',
  'к': 'to',
  'по': 'by',
  'у': 'at',
  'я': 'I',
  'ты': 'you',
  'он': 'he',
  'она': 'she',
  'оно': 'it',
  'мы': 'we',
  'они': 'they',
  'мне': 'to me',
  'меня': 'me',
  'тебя': 'you',
  'тебе': 'to you',
  'мой': 'my',
  'моя': 'my',
  'моё': 'my',
  'мои': 'my',
  'твой': 'your',
  'твоя': 'your',
  'твоё': 'your',
  'твои': 'your',
  'этот': 'this',
  'эта': 'this',
  'это': 'this',
  'эти': 'these',
  'есть': 'is',
  'быть': 'be',
  'где': 'where',
  'кто': 'who',
  'что': 'what',
  'как': 'how',
  'когда': 'when',
  'сейчас': 'now',
  'сегодня': 'today',
  'завтра': 'tomorrow',
  'вчера': 'yesterday',
  'никогда': 'never',
  'здесь': 'here',
  'там': 'there',
  'наверху': 'upstairs',
  'внизу': 'downstairs',
  'да': 'yes',
  'нет': 'no',
  'пожалуйста': 'please',
  'могу': 'can',
  'сделаю': 'will do',
  'делаю': 'do',
  'делать': 'do',
  'учишься': 'study',
  'учить': 'study',
  'читать': 'read',
  'играю': 'play',
  'идти': 'go',
  'живу': 'live',
  'жить': 'live',
  'нравишься': 'like',
  'милая': 'cute',
  'милый': 'cute',
  'молодой': 'young',
  'маленький': 'small',
  'короткий': 'short',
  'холодно': 'cold',
  'громко': 'loudly',
  'пустой': 'empty',
  'достаточно': 'enough',
  'вместе': 'together',
  'со': 'with',
  'мной': 'me',
  'большое': 'big',
  'спасибо': 'thanks',
  'будьте': 'be',
  'здоровы': 'well',
  'доброе': 'good',
  'добрый': 'good',
  'вечер': 'evening',
  'утро': 'morning',
  'день': 'day',
  'спокойной': 'good',
  'ночи': 'night',
  'свидания': 'goodbye',
  'скорого': 'soon',
  'увидимся': 'see you',
  'плохо': 'bad',
  'ничего': 'nothing',
  'страшного': 'serious',
  'конечно': 'of course',
  'правильно': 'correct',
  'повторите': 'repeat',
  'медленнее': 'more slowly',
  'немного': 'a little',
  'много': 'a lot',
  'приятно': 'nice',
  'познакомиться': 'to meet',
  'вы': 'you',
  'откуда': 'from where',
  'помогите': 'help',
  'близко': 'near',
  'далеко': 'far',
  'направо': 'right',
  'налево': 'left',
  'прямо': 'straight',
  'вызовите': 'call',
  'скорую': 'ambulance',
  'помощь': 'help',
  'сколько': 'how much',
  'стоит': 'costs',
  'дорого': 'expensive',
  'дёшево': 'cheap',
  'можно': 'can I',
  'оплатить': 'pay',
  'картой': 'by card',
  'хочу': 'want',
  'остро': 'spicy',
  'который': 'what',
  'час': 'time',
  'всё': 'everything',
  'хорошо': 'fine',
  'два': 'two',
  'три': 'three',
  'четыре': 'four',
  'пять': 'five',
  'шесть': 'six',
  'семь': 'seven',
  'восемь': 'eight',
  'девять': 'nine',
  'десять': 'ten',
  'одиннадцать': 'eleven',
  'двенадцать': 'twelve',
  'пятнадцать': 'fifteen',
  'двадцать': 'twenty',
  'тридцать': 'thirty',
  'пятьдесят': 'fifty',
  'сто': 'one hundred',
  'пятьсот': 'five hundred',
  'тысяча': 'one thousand',
  'евро': 'euros',
  'цент': 'cent',
  'центов': 'cents',
  'лари': 'lari',
  'тетри': 'tetri',
  'динар': 'dinar',
  'динаров': 'dinars',
  'пара': 'para',
  'лира': 'lira',
  'лир': 'lira',
  'куруш': 'kurus',
  'итого': 'total',
  'килограмм': 'a kilogram',
  'минут': 'minutes',
};

function capitalizeLikeSource(source: string, value: string): string {
  if (!source) return value;
  const first = source[0];
  if (first === first.toLocaleUpperCase('ru')) {
    return value.charAt(0).toUpperCase() + value.slice(1);
  }
  return value;
}

function translateByPattern(value: string): string | null {
  const lower = value.toLocaleLowerCase('ru-RU');

  const hereMatch = lower.match(/^(.+)\s+здесь$/);
  if (hereMatch) return `${translateRussianMeaningToEnglish(hereMatch[1])} is here`;

  const thereMatch = lower.match(/^(.+)\s+там$/);
  if (thereMatch) return `${translateRussianMeaningToEnglish(thereMatch[1])} is there`;

  const whereMatch = lower.match(/^где\s+(.+)$/);
  if (whereMatch) return `where is ${translateRussianMeaningToEnglish(whereMatch[1])}`;

  const totalMatch = lower.match(/^итого\s+(.+)$/);
  if (totalMatch) return `total: ${translateRussianMeaningToEnglish(totalMatch[1])}`;

  const kiloPriceMatch = lower.match(/^килограмм\s+стоит\s+(.+)$/);
  if (kiloPriceMatch) return `a kilogram costs ${translateRussianMeaningToEnglish(kiloPriceMatch[1])}`;

  const canCardMatch = lower.match(/^можно\s+(.+)\?$/);
  if (canCardMatch) return `can I ${translateRussianMeaningToEnglish(canCardMatch[1])}?`;

  const yesMatch = lower.match(/^да,\s+(.+)$/);
  if (yesMatch) return `yes, ${translateRussianMeaningToEnglish(yesMatch[1])}`;

  const thisIsMatch = lower.match(/^это\s+(.+)$/);
  if (thisIsMatch) return `this is ${translateRussianMeaningToEnglish(thisIsMatch[1])}`;

  const thisIsNotMatch = lower.match(/^это\s+не\s+(.+)$/);
  if (thisIsNotMatch) return `this is not ${translateRussianMeaningToEnglish(thisIsNotMatch[1])}`;

  const hereIsMatch = lower.match(/^вот\s+(.+)$/);
  if (hereIsMatch) return `here is ${translateRussianMeaningToEnglish(hereIsMatch[1])}`;

  const giveMeMatch = lower.match(/^дай мне\s+(.+)$/);
  if (giveMeMatch) return `give me ${translateRussianMeaningToEnglish(giveMeMatch[1])}`;

  const iNeedMatch = lower.match(/^мне нужн(?:ы|а|о|ен)\s+(.+)$/);
  if (iNeedMatch) return `I need ${translateRussianMeaningToEnglish(iNeedMatch[1])}`;

  const iHaveMatch = lower.match(/^у меня есть\s+(.+)$/);
  if (iHaveMatch) return `I have ${translateRussianMeaningToEnglish(iHaveMatch[1])}`;

  const iLikeMatch = lower.match(/^мне нравится\s+(.+)$/);
  if (iLikeMatch) return `I like ${translateRussianMeaningToEnglish(iLikeMatch[1])}`;

  const iWantMatch = lower.match(/^я хочу\s+(.+)$/);
  if (iWantMatch) return `I want ${translateRussianMeaningToEnglish(iWantMatch[1])}`;

  const wantMatch = lower.match(/^хочу\s+(.+)$/);
  if (wantMatch) return `I want ${translateRussianMeaningToEnglish(wantMatch[1])}`;

  const moreMatch = lower.match(/^ещё\s+(.+)$/);
  if (moreMatch) return `more ${translateRussianMeaningToEnglish(moreMatch[1])}`;

  const oneThingMatch = lower.match(/^(один|одна|одно)\s+(.+)$/);
  if (oneThingMatch) return `one ${translateRussianMeaningToEnglish(oneThingMatch[2])}`;

  const veryMatch = lower.match(/^очень\s+(.+)$/);
  if (veryMatch) return `very ${translateRussianMeaningToEnglish(veryMatch[1])}`;

  const tooMatch = lower.match(/^слишком\s+(.+)$/);
  if (tooMatch) return `too ${translateRussianMeaningToEnglish(tooMatch[1])}`;

  const pleaseMatch = lower.match(/^(.+),\s*пожалуйста$/);
  if (pleaseMatch) return `${translateRussianMeaningToEnglish(pleaseMatch[1])}, please`;

  const myNameIsMatch = lower.match(/^меня зовут\s+(.+)$/);
  if (myNameIsMatch) return `my name is ${myNameIsMatch[1]}`;

  const worksMatch = lower.match(/^(.+)\s+работает$/);
  if (worksMatch) return `${translateRussianMeaningToEnglish(worksMatch[1])} works`;

  const pronounNegativeMatch = lower.match(/^(он|она|оно|они)\s+не$/);
  if (pronounNegativeMatch) {
    const pronounMap: Record<string, string> = { 'он': 'he', 'она': 'she', 'оно': 'it', 'они': 'they' };
    return `${pronounMap[pronounNegativeMatch[1]]} is not`;
  }

  const notPronounMatch = lower.match(/^не\s+(он|она|оно|они)$/);
  if (notPronounMatch) {
    const pronounObjectMap: Record<string, string> = { 'он': 'him', 'она': 'her', 'оно': 'it', 'они': 'them' };
    return `not ${pronounObjectMap[notPronounMatch[1]]}`;
  }

  return null;
}

export function translateRussianMeaningToEnglish(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return '';

  const exact = EXACT_MEANING_OVERRIDES[trimmed.toLocaleLowerCase('ru-RU')];
  if (exact) return capitalizeLikeSource(trimmed, exact);

  const patterned = translateByPattern(trimmed);
  if (patterned) return capitalizeLikeSource(trimmed, patterned);

  const translated = trimmed
    .split(/(\s+|[.,!?;:()])/)
    .map((token) => {
      const normalized = token.toLocaleLowerCase('ru-RU');
      return TOKEN_MAP[normalized] ?? token;
    })
    .join('')
    .replace(/\s+/g, ' ')
    .trim();

  return capitalizeLikeSource(trimmed, translated);
}
